### PR TITLE
Split models.py into several files

### PR DESCRIPTION
**Pull request by Hwesta**
locations/models.py is approaching 2000 lines long. Move it to a models directory and split into several files.

Most models get a file, with some similar models grouped together in the same file. Use init.py used to maintain the same import structure.

The first commit is just models.py copied into several files with trimmed imports, to make it easier to rebase. The second commit is the changes required to make this work (notably adding app_label = 'locations') as well as pep8 updates. They will probably be rebased together when committed.

### CODE REVIEW

**Comment by mistydemeo** [comment]
:thumbsup: 

I am not looking forward to rebasing FEDORA/Islandora on top of this if this goes in first though. :crying_cat_face:

**Comment by Hwesta** [comment]
Rebased on top of #7 and #22

**Comment by mistydemeo** [comment]
Still :thumbsup: 

Though maybe this should be made one commit so we don't leave the SS broken in between commits?

**Comment by Hwesta** [comment]
Okay, I'll squash the first two commits.

**Pull request merged**
