### PR TITLE
Update metsrw to v0.2.4

### PR DESCRIPTION
**Pull request by sevein**
Connects to https://github.com/archivematica/Issues/issues/260.

### CODE REVIEW

**Review by ross-spencer — COMMENTED** [review]
Might be related to my question in the `metsrw` review, but we've normally been referring to the package version, https://github.com/artefactual/archivematica/blob/stable/1.8.x/src/MCPClient/requirements/base.txt#L9 we we want to do the same in the Storage Service?

**Comment by sevein** [comment]
Yay! It's just that the usual process is to submit the PRs pointing to the commit so we enable testing and people can confirm the behaviour before making the actual release upstream.

**Comment by sevein** [comment]
I should have mentioned that in the description, sorry.
PR is meant to be updated pointing to the final tag, once the fix is confirmed!

**Review by ross-spencer — APPROVED** [review]
Ah! That makes sense. Useful to see the procedure play out. Thanks for the info! :+1:

**Pull request merged**
