### PR TITLE
Disable automatic lang selection

### PR DESCRIPTION
**Pull request by sevein**
This closes https://github.com/artefactual/archivematica/issues/723.
Related: https://github.com/artefactual/archivematica/pull/748.

### CODE REVIEW

**Review by jraddaoui — APPROVED** [review]
Not a big deal as I guess it's not being used anywhere else, but we could set the settings language in the request instead of removing it.

Thanks @sevein

**Comment by sevein** [comment]
> Not a big deal as I guess it's not being used anywhere else, but we could set the settings language in the request instead of removing it.

I agree, it feels like a hack. Removing the header from the request is not ideal but it seems to be the only way that doesn't require us to bundle our own version of [LocaleMiddleware](https://github.com/django/django/blob/stable/1.8.x/django/middleware/locale.py#L29-L34).

Perhaps take a look at the link and see if you can find a better way. This is in any case a temporary solution that we're including in AM 1.7. But it'd be good to see if it has any unexpected impact.

**Comment by sevein** [comment]
@helenst, I'm curious to hear your opinion :)

**Comment by helenst** [comment]
@sevein so by doing it this way (rather than removing LocaleMiddleware) the user can still select their language preference explicitly in the admin, it just won't use the header value (i.e. the browser setting) - is that right? (I'm just running the ansible stuff so I can try it out). It seems like a reasonable way to deal with it.

**Review by helenst — APPROVED** [review]

**Comment by sevein** [comment]
@helenst, that's right! The current state of translations in Spanish and French is so poor right now that we decided it doesn't make sense to offer it unless the user explicitly wants to choose it.

You may want to try https://github.com/artefactual-labs/am instead (Compose) - it's so much faster!

**Comment by helenst** [comment]
@sevein Thanks, I'll give that a try!

**Comment by sevein** [comment]
9954f12a92b5c408eb26c5e82c736ef68e173ed7

**Pull request merged**
