### PR TITLE
#10662 GPG encrypted storage

### PR DESCRIPTION
**Pull request by jrwdunham**
Allows for creation of a GPG-encrypted space with AIP Storage and Transfer Backlog-purposed locations such that all packages placed in those locations are encrypted upon entry and decrypted on exit. Also includes an interface for managing (creating, importing, viewing, deleting) GPG keys.

See also

- https://github.com/artefactual/archivematica/pull/616
- https://github.com/artefactual-labs/archivematica-acceptance-tests/pull/9
- https://github.com/artefactual-labs/ansible-archivematica-src/pull/109

### CODE REVIEW

**Comment by jrwdunham** [comment]
The test at test_gpg.py is not passing. It is old and was written for an earlier iteration. New tests may need to be written (though the relevant acceptance tests should pass).

**Comment by sevein** [comment]
@scollazo the Jenkins build is stuck, what should we do?

**Comment by scollazo** [comment]
Seems it wasn't stuck, but slow. I'll check why the gpg tests took more than 3 hours.

**Comment by jhsimpson** [comment]
replaced by #198

**Pull request closed without merging**
