### PR TITLE
Delete DIPs

### PR DESCRIPTION
**Pull request by jrwdunham**
UPDATE(@sevein): see comments below for more details on how this is being implemented!

Connected to #319.

### CODE REVIEW

**Comment by sevein** [comment]
Adding reviewers so the approach can be validated. JD originally updated `PACKAGE_TYPE_CAN_DELETE` so DIPs could be deleted following the exact same workflow than other package types, i.e. deletion request is submitted, administrator confirms deletion, etc...

As per Sarah's request, I've changed it so the confirmation is not required. The "Delete" links appear next to DIPs in the package list sending the request directly to q new `package_delete` view which performs the deletion. The template has been updated so the deletion button is hidden when the package status is `DELETED`. I was surprised to see that's not the case for other action buttons.

If this looks okay for you let me know, I wasn't entirely sure if this is the right thing to do.

I've added a bunch of tests.

**Review by sevein — COMMENTED** [review]
CC @artefactual/amcr

**Comment by ablwr** [comment]
Code looks good and it works fine. I wonder if we should have an additional pop-up "Are you sure you want to delete this DIP?", especially because this is such a leap from the existing flow of request deletion, confirm deletion steps we have for AIPs.

**Comment by sevein** [comment]
@ablwr, pop-up added! I've used the bs2 dialog support, this is how it looks like...

image

**Comment by ablwr** [comment]
:tada: :tada: :tada:

**Comment by ablwr** [comment]
This works for me in Chrome but not in Firefox. In Firefox, it just doesn't pop up and goes straight through to deleting.

Another thing... after I hit delete, "download" is still visible. We should hide it, right? The status does update to Deleted though. Will those linger around forever, how would someone clear those out if that's their intent?

**Comment by sevein** [comment]
> This works for me in Chrome but not in Firefox. In Firefox, it just doesn't pop up and goes straight through to deleting.

Ops, fixed now, thanks for testing that!

> Another thing... after I hit delete, "download" is still visible. We should hide it, right? The status does update to Deleted though. Will those linger around forever, how would someone clear those out if that's their intent?

Ok, see the extra commit. It was also affecting AIPs.

**Comment by ablwr** [comment]
@sevein OK it works! Although it is firing twice for me in both Firefox/Chrome if I hit cancel, it asks again for me to approve or cancel. Lemme look at the js...

**Comment by ablwr** [comment]
Oops, forgot to press "Comment" here. :laughing: 

Yeah, the JS fires for every DIP on the page instead of the one that is being clicked!

**Comment by sevein** [comment]
:man_facepalming: sorry I'll take a look, my js skillz are gone haha

**Comment by sevein** [comment]
Ok @ablwr I've changed the code a bit, the previous attempt was a hot mess because the callback was being triggered on each match. Now using `jQuery.each` instead.

```javascript
    $("form.submit-confirm").each(function(index, target) {
      var $form = $(target);
      var $modal = $form.find(".confirm-modal");
      $form.on("click", "button[type=submit]", function(event) {
          var $button = $(event.target);
	  if ($button.parents(".confirm-modal").length) {
            return true;
          }
          event.preventDefault();
          $modal.modal("show");
      });
```

**Review by ablwr — APPROVED** [review]

**Comment by ablwr** [comment]
Just tested and seems all good now!

**Pull request merged**
