### PR TITLE
Better Pipeline.remote_name handling

### PR DESCRIPTION
**Pull request by sevein**
Read the commits for more details.

This pull request mitigates #266 (related to #236).

### CODE REVIEW

**Comment by scollazo** [comment]
I think this will fail if the ss uses ssl with self-signed certificates.

**Comment by sevein** [comment]
> I think this will fail if the ss uses ssl with self-signed certificates.

Ok, thank you @scollazo. I'll add a `INSECURE_SKIP_VERIFY` toggle.

**Comment by sevein** [comment]
@scollazo see c8c5b5f70bb8c6b9e499ff880c11da2572913eda.

**Review by ross-spencer — COMMENTED** [review]
I can't see anything too major, suggestions:

* parse_url() should be changed to parse_and_fix_url(): Rationale: the function name is confusing vs. other urlparse()-like functions out there (we're not just parsing). We're adding something new, e.g. making sure http is explicitly added if the scheme is empty.

* url = parse_url(...), url = uri._replace(...) any instances where you're pairing these two operations (I count three?) I would change this into a single helper function to do both operations at the same time, turning the two lines into two. This is a personal preference whenever I see the same variable being manipulated like this within the same number of lines, so it wraps it in a way that looks more deliberate. It may also help unit testing.

* url as a variable name could be improved (maybe from golang experience - url is just a difficult variable name.

* Lines 104 and 344 in helpers.py the function call is constructed using a parameter:

     verify=not 

* not is a keyword in Python and unless this library explicitly requests the use of the word not, over (?) then i would suggest changing that to another value. (I can't remember not being used like this - so could just be me)

**Comment by sevein** [comment]
@ross-spencer, I've addressed your comments.

I've used vcrpy to test the new methods. It's a handy testing tool that Holly introduced a while ago where you can go beyond unit tests by recording the HTTP requests and responses and keep in them in the repo as fixtures.

**Review by ross-spencer — APPROVED** [review]
Looks good @sevein thx for the additional changes.

**Pull request merged**
