### PR TITLE
Fix for selecting region us-east-1 with S3

### PR DESCRIPTION
**Pull request by fitnycdigitalinitiatives**
@ross-spencer 
Resubmission of a broken [pull-request](https://github.com/artefactual/archivematica-storage-service/pull/488).

Addresses [archivematica/Issues#922](https://github.com/archivematica/Issues/issues/922) where us-east-1 cannot be selected as for S3 region.

Sorry for the resubmission! I messed up the rebase.

### CODE REVIEW

**Comment by ross-spencer** [comment]
**NB.** #498 and #499 are part of a number of PRs also touching S3. For ease of merging we should wait until those are merged at this point to follow up, and make the necessary changes to merge this into `qa/0.x` for `1.11`. Will keep folks posted.

**Comment by fitnycdigitalinitiatives** [comment]
@ross-spencer Sounds good. I was also thinking about submitting a very simple PR to enable DIP Storage for S3. Do you think that would need to be separate, because it also seems like it could fit in with #499, and enable that in addition to transfer source?

**Comment by ross-spencer** [comment]
Hi @fitnycdigitalinitiatives from our perspective with the feature freeze now, a good target for that would be Archivematica 1.12, if you could log a ticket first describing the feature that would be great. If you had the capacity to do the PR around late January/early Feb too that would be great as well and increase the chances of making it into the system and being available early in `qa/1.x` -> `1.12`.

**Comment by ross-spencer** [comment]
Hi Joseph (@fitnycdigitalinitiatives) we're looking good to add the final changes to this PR now. When you update your branches, and rebase to `qa/0.x` you'll see a merge conflict like this:
```
<<<<<<< HEAD
            self.resource.create_bucket(
                Bucket=self.bucket_name,
                CreateBucketConfiguration={"LocationConstraint": self.region},
            )
=======
            # LocationConstraint cannot be specified if it us-east-1 because it is the default, see: https://github.com/boto/boto3/issues/125
            if self.region == "us-east-1":
                self.client.create_bucket(Bucket=self._bucket_name())
            else:
                self.client.create_bucket(
                    Bucket=self._bucket_name(),
                    CreateBucketConfiguration={"LocationConstraint": self.region},
                )
>>>>>>> check region when creating s3 bucket
```
Which shouldn't be too bad to resolve. 

I wonder too if `if self.region == "us-east-1":` might benefit from being `if self.region.lower() == "us-east-1":`?

Can you submit the changes, and once they are done we'll get this approved and merged. 

We appreciate your patience with this one, it's a small but good fix but was caught up with a few other conflicts which I know for me when I'm contributing code adds an extra element of asking "why can't this be easier?!" - I'm gonna try and acknowledge some of this at my talk at Archivematica Con 2020 if you can make it there ([link](https://wiki.archivematica.org/Community/Camps/Brooklyn2020)). Hopefully it will generate some good discussion/conversation. 

Thanks in advance for the changes, and happy $HOLIDAYS before hand.

**Comment by fitnycdigitalinitiatives** [comment]
Hi @ross-spencer,

Sorry for the delayed response. Hope you had a nice holiday. I think I was able to figure out the rebase correctly this time, and also added that helpful `lower()` into it. I rebased from `qa/0.x` as you instructed but see now there are still some conflicts with some requirement files—is that how it should be?

Will definitely be at Archivematica Con 2020. I see registration just opened. Look forward to your talk!

**Comment by ross-spencer** [comment]
Thank you Joseph! Hope yours was good too. And I look forward to saying hello later in the year in person. I am looking forward to the free-form parts of day 1 for sure and hope for some good hacking!

I'm not sure what happened with the rebase other than it still seems to want to be against `stable/0.15.0` but that's okay - I think your PR came in during the perfect storm of S3 updates, but the commit is good, and I was able to cherry-pick that against `qa` [here](https://github.com/artefactual/archivematica-storage-service/pull/515). So we'll get that merged pretty much now! :D - thank you so much for the contribution and your patience with the process.

**Comment by fitnycdigitalinitiatives** [comment]
Ok, thanks. So in the future, if I make a pull-request it should be off the qa branch rather than the current stable branch?

**Comment by ross-spencer** [comment]
That's a pretty good rule of thumb. If we ever need to place something in a `stable/branch` e.g. for a maintenance release, we can cherry-pick backwards if necessary. But yep, our `qa` branch is always the branch we cut the next release from.

**Pull request closed without merging**
