### PR TITLE
Add config docs to install/README.md

### PR DESCRIPTION
**Pull request by sevein**
See [install/README.md](https://github.com/artefactual/archivematica-storage-service/blob/dev/docs-config/install/README.md).

### CODE REVIEW

**Review by sallain — APPROVED** [review]
LGTM!

**Comment by sevein** [comment]
I've updated this PR to align it to the changes suggested by @jhsimpson in AM (see https://github.com/artefactual/archivematica/pull/856).

**Review by jhsimpson — APPROVED** [review]
great!

**Comment by sevein** [comment]
eebc908 in `stable/0.11.x`

**Pull request merged**
