### PR TITLE
Delete create_testuser signal handler

### PR DESCRIPTION
**Pull request by sevein**
This commit removes the signal handler that was responsible for creating the
`test` superuser. It is still possible to create a superuser from the
command-line interface.

The `base` fixture file is updated so it includes a new superuser. Previously,
the tests were relying on user created by the `create_testuser` signal handler.

Connected to #286

### CODE REVIEW

**Review by jrwdunham — COMMENTED** [review]
@sevein Can you modify #286 to describe *why* this is a problem? Is it an issue of not wanting the default behaviour being creation of a superuser with a very guessable password?

Also, I'm wondering if your fixtures solution will still work if we update Django in the future. That is, does the hashed value of the "test" password change if Django uses a different hashing algorithm?

Finally, are you saying that merging this will require making mods in all of our deployment tools (ansible, packages, docker) so that they become responsible for creating this "test" user?

**Comment by sevein** [comment]
> @sevein Can you modify #286 to describe why this is a problem? Is it an issue of not wanting the default behaviour being creation of a superuser with a very guessable password?

Done. I hope it's clearer now.

> Also, I'm wondering if your fixtures solution will still work if we update Django in the future. That is, does the hashed value of the "test" password change if Django uses a different hashing algorithm?

I'm using `pbkdf2_sha256`which is still listed as a [supported hasher in Django v2.0](https://docs.djangoproject.com/en/2.0/topics/auth/passwords/#included-hashers). If this becomes a problem in the future I think it's safe to assume that the hasher identifier will raise some kind of exception and the test will break when we perform authentication, i.e. we wouldn't be seeing false positives I believe.

> Finally, are you saying that merging this will require making mods in all of our deployment tools (ansible, packages, docker) so that they become responsible for creating this "test" user?

I think that we're going to be solving this differently depending on the distribution type:

- Packages: we're updating the installation instructions (docs.archivematica.org) so the user can create the superuser manually.

- Ansible: I think that we can try to extend @mamedin's solution in https://github.com/artefactual-labs/ansible-archivematica-src/pull/162.

**Comment by sevein** [comment]
@jrwdunham one clarification: I think that https://github.com/artefactual/archivematica-docs/pull/178 could be enough for now when it comes to explaining users how the installation process changes in debs/rpms/ansible without making actual changes in their sources.

Perhaps @mamedin's effort to automate the installation via Ansible (see https://github.com/artefactual-labs/ansible-archivematica-src/pull/162) may need some extra care once this is merged.

IMO this PR is ready to merge.

**Review by jrwdunham — APPROVED** [review]
LGTM

**Comment by sevein** [comment]
2976d2526ddb3e680eeaca80b04c8dc5f80f8b0f

**Pull request closed without merging**
