### PR TITLE
package.py : Use parallel bag validation processes

### PR DESCRIPTION
**Pull request by tw4l**
Suggested change to increase speed of bag validation. Parallel validation processes would help immensely in speeding up, e.g., scanall Fixity app scans. It's worth double-checking but my understanding of the way bagit-python implements multithreading means that if the machine is unable to dedicate 4 cores to the task, it will simply allocate what is available.

processes=4 is arbitrary (instead of, say, 8) but seemed like a reasonable number. The ideal number would likely depend on local setup.

### CODE REVIEW

**Comment by tw4l** [comment]
Yes

**Comment by scollazo** [comment]
Hi Timothy, thanks for signing the CLA

ok to test

**Comment by jhsimpson** [comment]
The jenkins check is failing because of a bug in the ubuntu 14.04 version of python-pip, not related to this branch.

@timothyryanwalsh , if you rebase this branch on qa/0.x, the checks should pass next time.

**Comment by tw4l** [comment]
Resubmitted as PR [177](https://github.com/artefactual/archivematica-storage-service/pull/177/) against qa/0.x

**Comment by Hwesta** [comment]
As a tip, Github now allows you to change the branch a PR was opened against using the Edit next to the title. Next time you can try that instead of opening a new PR. :)

**Comment by tw4l** [comment]
Oh, good to know! Thanks Holly :)

**Pull request closed without merging**
