### PR TITLE
API: Fix package location filtering

### LINKED ISSUE #298: Problem: API package filtering by location doesn't work
PackageResource contains its related LocationResource in a field called `current_location` but it's being added to the filtering options as `location` in https://github.com/artefactual/archivematica-storage-service/blob/stable/0.11.x/storage_service/locations/api/resources.py#L470.

Currently trying to filter over the `location` field, no results are being filtered:
```
{{ss:url}}/api/v2/file/?location__uuid=9084c5ef-349d-4bef-80cd-37c9aead55c7

{
    "meta": {
        "limit": 20,
        "next": "/api/v2/file/?limit=20&offset=20",
        "offset": 0,
        "previous": null,
        "total_count": 39
    },
    "objects": [
        {
            "current_full_path": "/var/archivematica/sharedDirectory/www/AIPsStore/bd1b/f9dd/aaaf/47df/9f31/c19e/b605/d64d/test_2-bd1bf9dd-aaaf-47df-9f31-c19eb605d64d",
            "current_location": "/api/v2/location/e9a08ce2-4e8e-4e01-bdea-09d8d8deff8b/",
            "current_path": "bd1b/f9dd/aaaf/47df/9f31/c19e/b605/d64d/test_2-bd1bf9dd-aaaf-47df-9f31-c19eb605d64d",
            "encrypted": false,
            "misc_attributes": {},
            "origin_pipeline": "/api/v2/pipeline/ad174753-6776-47e2-9a12-ac37837e5128/",
            "package_type": "AIP",
            "related_packages": [],
            "replicas": [],
            "replicated_package": null,
            "resource_uri": "/api/v2/file/bd1bf9dd-aaaf-47df-9f31-c19eb605d64d/",
            "size": 108440123,
            "status": "UPLOADED",
            "uuid": "bd1bf9dd-aaaf-47df-9f31-c19eb605d64d"
        },
        {
            "current_full_path": "/var/archivematica/sharedDirectory/www/AIPsStore/753c/223f/b23b/4a2f/8db2/c5c1/56ca/6505/test-753c223f-b23b-4a2f-8db2-c5c156ca6505",
            "current_location": "/api/v2/location/e9a08ce2-4e8e-4e01-bdea-09d8d8deff8b/",
            "current_path": "753c/223f/b23b/4a2f/8db2/c5c1/56ca/6505/test-753c223f-b23b-4a2f-8db2-c5c156ca6505",
            "encrypted": false,
            "misc_attributes": {},
            "origin_pipeline": "/api/v2/pipeline/ad174753-6776-47e2-9a12-ac37837e5128/",
            "package_type": "AIP",
            "related_packages": [],
            "replicas": [],
            "replicated_package": null,
            "resource_uri": "/api/v2/file/753c223f-b23b-4a2f-8db2-c5c156ca6505/",
            "size": 53529006,
            "status": "UPLOADED",
            "uuid": "753c223f-b23b-4a2f-8db2-c5c156ca6505"
        },
        ...
}
```
And trying to filter over `current_location` returns the following error:
```
{{ss:url}}/api/v2/file/?current_location__uuid=9084c5ef-349d-4bef-80cd-37c9aead55c7

{
    "error": "The 'current_location' field does not allow filtering."
}

### PR DESCRIPTION
**Pull request by jraddaoui**
Fixes #298

### CODE REVIEW

**Comment by jraddaoui** [comment]
Needed and included in https://github.com/artefactual/archivematica-storage-service/pull/300

**Comment by jraddaoui** [comment]
Hi @jhsimpson and @sevein, are we on time to include this minor fix into the next release?

**Comment by sevein** [comment]
I've added it to the AM17 project board to give it some visibility. This way it can be discussed in our weekly meeting.

**Review by sevein — APPROVED** [review]

**Comment by jraddaoui** [comment]
cc6a11da31cbe87dcd4ce3177e22152e11c764ee in qa/0.x

**Pull request merged**
