### PR TITLE
Stream HTTP response to avoid loading large files into memory

### PR DESCRIPTION
**Pull request by marktriggs**
Addresses https://github.com/archivematica/Issues/issues/113

### CODE REVIEW

**Comment by ross-spencer** [comment]
This looks good @marktriggs I will cherry-pick it into the am dev branch in gitolite to test. 

I didn't realize it would be this simple via the requests library so I've just been looking at the docs. Do you think it necessary to add `with` to the request, e.g. via the docs:

> If you set stream to True when making a request, Requests cannot release the connection back to the pool unless you consume all the data or call Response.close. This can lead to inefficiency with connections. If you find yourself partially reading request bodies (or not reading them at all) while using stream=True, you should make the request within a with statement to ensure it’s always closed:
```
with requests.get('http://httpbin.org/get', stream=True) as r:
    # Do things with the response here.
```

**Comment by marktriggs** [comment]
Ah nice catch @ross-spencer; I think adding that `with` block would be the right thing to do.  My loop should have consumed all the data anyway, but an IO error writing to the file could get it into trouble and leak that connection, so best to be safe.

**Comment by sromkey** [comment]
Connected to https://github.com/archivematica/Issues/issues/113

**Comment by ross-spencer** [comment]
Cherry-picked for commit: de6ff565a503edb2fedb81348a078018225ea298 (Dataverse transfer feature). Thanks once again @marktriggs.

**Pull request closed without merging**
