### PR TITLE
Libffi is a runtime not build dependency

### PR DESCRIPTION
**Pull request by Hwesta**

### CODE REVIEW

**Comment by mistydemeo** [comment]
:+1:

**Comment by mistydemeo** [comment]
Wait - I'm confused. I thought that we installed dependencies as part of `dh_virtualenv`.

**Comment by mistydemeo** [comment]
e.g. during the buildphase.

**Comment by Hwesta** [comment]
Not the correct fix for this problem, see artefactual/archivematica#264

**Pull request closed without merging**
