### PR TITLE
Fix space browser when counter is disabled

### PR DESCRIPTION
**Pull request by mamedin**
Connects to issue https://github.com/archivematica/Issues/issues/657

### CODE REVIEW

**Comment by ross-spencer** [comment]
Hi @mamedin it looks like there is a failing unit test that you need to resolve with this PR first. I haven't looked at the cause, but let me know if I can help at all.

**Comment by sevein** [comment]
I'll give it a shot today!

**Review by mamedin — COMMENTED** [review]
Thanks Jesús, it works fine :)

**Review by sevein — APPROVED** [review]
:+1:

**Pull request merged**
