### PR TITLE
Improvements to s3 plugin

### PR DESCRIPTION
**Pull request by helenst**
Addresses https://github.com/archivematica/Issues/issues/712 - also related to https://github.com/archivematica/Issues/issues/639

I've also added some tests for the browse feature, and added an optional bucket name field (which makes it easier to set up policies etc. when the system is being automatically deployed, rather than use the space id)

I've bundled these few small fixes in together but please let me know if there's anything you'd like separately?

Connected to archivematica/Issues#558
Connected to archivematica/Issues#975
Connected to archivematica/Issues#712

### CODE REVIEW

**Review by ross-spencer — CHANGES_REQUESTED** [review]
Hi @helenst following on the `1.11` triage work to see what features we'll be able to get into the release I have been looking at the three enhancements here. 

Overall, the changes are starting to look good, but there have been significant shifts again between when this was developed and where the `1.10` release landed. These are creating merge conflicts and I think affecting the functionality a little too. Can you rebase against the `qa` branches and ensure that the features as you developed them are working as anticipated? 

I have had to find commits to test against today and am using the following to verify some of this work:

Testing with storage service: c63ee0043860491583a0e3b01e8b6c9ac47983b5
Archivematica: https://github.com/artefactual/archivematica/commit/60ff3249a2ae8b9539591d0efa57025f25322be8

For the three separate enhancements I wonder if it would be best to re-work this into three separate PRs based on the existing storage service `qa` branch as you allude to in the submission?

Additional comments below:

## Naming an S3 bucket

Naming a bucket works nearly as we would hope, though it would be good to have the resilience of the current service where a bucket is created if it doesn't exist. 

Connected to https://github.com/archivematica/Issues/issues/558

## S3 as a transfer source

The browse piece of this is shaping up, but are we expecting to have the empty braces in the transfer browser as per here: 

image

It would be great to figure out what is needed to remove those.

I am also not able to initiate a transfer, so I suspect if this is in production at Wellcome I'm missing some configuration locally.  

I've created a separate issue for the feature: Connected to https://github.com/archivematica/Issues/issues/975

## Leaving authentication details blank

There isn't too much that is controversial here, though in the [ticket](https://github.com/archivematica/Issues/issues/712) it would be great to elaborate on a method to test against a docker-based development environment. 

Possibly in the UI, but at a minimum in the documentation I feel a similar elaboration on how users might make S3 work without authentication would help. A note or a warning perhaps that lets users know that if certain fields are left blank then they will need to configure that outside of the storage service. Does that sound sensible?

Connected to https://github.com/archivematica/Issues/issues/712

---

How does this sound? Does it seem like something Wellcome can do, or begin to look at to start shaping these for a `1.11` release of Archivematica? 

We're just getting to grips with the extent of the current submissions, I don't think we need everything perfect for next week, but some indication about what seems reasonable, and is still desired would be great. We'll do the majority of the `1.11` work between the end of November and December *fingers crossed*.

**Comment by helenst** [comment]
@ross-spencer I've rebased, and will see if I can sensibly separate these into their own PRs. I think I may have fixed the blank parentheses in dashboard and forgotten to include the PR for that. I'll create a PR for that too :)

**Comment by ross-spencer** [comment]
Thanks @helenst this it great. I'll ask internally what our next steps are with regards to communicating `1.11` milestones (I think you're just a bit ahead of the curve here!) - it looks like this work will fall nicely within those thresholds - it might be useful to you for other PRs or potential PRs. Will get back to you!

**Comment by helenst** [comment]
@ross-spencer It looks as if that issue with the parentheses was already fixed here https://github.com/artefactual/archivematica/commit/a889605d8

**Comment by helenst** [comment]
Closing in favour of separate PRs #497 #498 #499

**Pull request closed without merging**
