### PR TITLE
Package: prefix METS pointer elements

### PR DESCRIPTION
**Pull request by mistydemeo**

### CODE REVIEW

**Comment by mistydemeo** [comment]
It's possibly an oversight that these weren't assigned a namespace when adding these elements before; because pointer files had no default namespace, it was possible to omit namespaces and still have them considered METS elements.

**Comment by Hwesta** [comment]
`common/utils.py` also touches pointer files and namespaces.

**Comment by mistydemeo** [comment]
Good catch, updated.

**Comment by Hwesta** [comment]
And it looks like `lockssomatic.py` also modifies the pointer file.  No other files use `[Sub]Element` or `ElementMaker`

**Comment by mistydemeo** [comment]
Arg, also good catch. Updated, and also did some cleanup since this file predates `utils.PREFIX_NS`.

**Comment by Hwesta** [comment]
:+1:

**Pull request merged**
